### ISSUE TITLE
On performance issues

### ISSUE THREAD

**Issue by Yang66g** [the-mirror-gdp/the-mirror#227] opened 2024-07-22 03:03 UTC
It's based on GDScript, which can lead to a low ceiling for the engine

**Comment by krnico** [comment] 2024-07-23 07:07
Potential to use GDExtension with other languages like C++ or Rust for heavy components in the future.

**Comment by RevoluPowered** [comment] 2024-08-03 03:38
We're not considering using rust, we have a C++ module already for the heavy components, please add more identifying information to the ticket and explain what issue you are having with performance, and give us the reproduction steps.

**Comment by RevoluPowered** [comment] 2024-09-16 18:04
Closing because it's not specific enough, we need a report with steps to reproduce specific performance issues we use C++ already in some area's that we found were 'hot' and heavy on performance.

**Closed as completed by RevoluPowered** 2024-09-16 18:04 UTC
